### ISSUE TITLE
The project doesn't work with Android Gradle plugin version 7.0.0-alpha15

### ISSUE THREAD

**Issue by nikolaykasyanov** [Kotlin/kmm-production-sample#16]
Hi folks,

first of all, thanks for this nice sample project.

I tried to open it today in the latest (at the time of writing) Arctic Fox 2020.3.1 Canary 15 (as far as I understand, the project is going to work neither in beta nor stable channles of Android Studio nor in the latest version of IDEA, please correct me if I'm wrong), and it demanded that I upgrade the plugin to alpha 15. After doing so, I'm getting following error in Android Studio:

```
org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/user/Developer/kmm-production-sample/androidApp/build.gradle.kts' line: 37
Script compilation error:
  Line 37:             initWith(getByName("debug"))
                       ^ Unresolved reference: initWith
```

Unfortunately I couldn't find any changelogs of Android Gradle plugin 7.0 alphas to find out why and with what it was removed/replaced.

**Comment by LouisCAD** [comment]
AGP maintainers unfortunately don't have the habit of telling that the API broke and how it changed, especially in the canary releases.

I just removed any reliance on `initWith` in other projects where I used it and wanted to use the latest AGP.

It might get fixed in Canary 16 though as they're reverting fixing stuff that got broken in Canary 15 of AGP 7.

**Comment by terrakok** [comment]
Fixed
